chore(deps): merge dependabot PR #1863
Bumps
[org.springframework.data:spring-data-elasticsearch](https://github.com/spring-projects/spring-data-elasticsearch)
from 6.0.5 to 6.1.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/spring-projects/spring-data-elasticsearch/releases">org.springframework.data:spring-data-elasticsearch's
releases</a>.</em></p>
<blockquote>
<h2>6.1.0</h2>
<h2>:green_book: Links</h2>
<ul>
<li><a
href="https://docs.spring.io/spring-data/elasticsearch/reference/6.1/">Spring
Data Elasticsearch 6.1.0 Reference documentation</a></li>
<li><a
href="https://docs.spring.io/spring-data/elasticsearch/reference/6.1/api/java/">Spring
Data Elasticsearch 6.1.0 Javadoc</a></li>
</ul>
<h2>:star: New Features</h2>
<ul>
<li>Allow IndexCoordinates in repositories <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/2506">#2506</a></li>
</ul>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li><code>routing=null</code> in queries when using elasticsearch client
9.3 <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/3278">#3278</a></li>
<li>Reactive saveAll errors are swallowed in
AbstractReactiveElasticsearchTemplate <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/3233">#3233</a></li>
<li>RequestConverter uses UpdateQuery.id for both document id and script
id <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/3231">#3231</a></li>
<li>AOT Processing Fails with NoClassDefFoundError for Apache HttpClient
4.x Classes <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/3203">#3203</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Update documentation for upcoming release <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/3286">#3286</a></li>
<li>Documentation incorrectly implies interface-based projections are
supported in repository queries <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/3261">#3261</a></li>
<li>Antora build failures <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/3199">#3199</a></li>
<li>Refine Antora-build <a
href="https://redirect.github.com/spring-projects/spring-data-build/issues/2797">#2797</a></li>
<li>Add Readme templates <a
href="https://redirect.github.com/spring-projects/spring-data-build/issues/2758">#2758</a></li>
</ul>
<h2>:hammer: Dependency Upgrades</h2>
<ul>
<li>Upgrade to Maven Wrapper 3.9.16 <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/3291">#3291</a></li>
<li>Upgrade to Elasticsearch REST Client 9.4.2 <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/3290">#3290</a></li>
<li>Upgrade to Elasticsearch 9.3.3 <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/3262">#3262</a></li>
<li>Upgrade Elasticsearch client to 9.3.2 <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/3259">#3259</a></li>
</ul>
<h2>6.1.0-RC1</h2>
<h2>:green_book: Links</h2>
<ul>
<li><a
href="https://docs.spring.io/spring-data/elasticsearch/reference/6.1/">Spring
Data Elasticsearch 6.1.0 Reference documentation</a></li>
<li><a
href="https://docs.spring.io/spring-data/elasticsearch/reference/6.1/api/java/">Spring
Data Elasticsearch 6.1.0 Javadoc</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Documentation incorrectly implies interface-based projections are
supported in repository queries <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/3261">#3261</a></li>
</ul>
<h2>:hammer: Dependency Upgrades</h2>
<ul>
<li>Upgrade to Elasticsearch 9.3.3 <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/3262">#3262</a></li>
<li>Upgrade Elasticsearch client to 9.3.2 <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/3259">#3259</a></li>
</ul>
<h2>6.1.0-M2</h2>
<h2>:green_book: Links</h2>
<ul>
<li><a
href="https://docs.spring.io/spring-data/elasticsearch/reference/6.1/">Spring
Data Elasticsearch 6.1.0 Reference documentation</a></li>
<li><a
href="https://docs.spring.io/spring-data/elasticsearch/reference/6.1/api/java/">Spring
Data Elasticsearch 6.1.0 Javadoc</a></li>
</ul>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>Reactive saveAll errors are swallowed in
AbstractReactiveElasticsearchTemplate <a
href="https://redirect.github.com/spring-projects/spring-data-elasticsearch/issues/3233">#3233</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Refine Antora-build <a
href="https://redirect.github.com/spring-projects/spring-data-build/issues/2797">#2797</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/spring-projects/spring-data-elasticsearch/commit/38ba9fd08ae4de9acb1aeac3e2f1d7810a2f3bd5"><code>38ba9fd</code></a>
Release version 6.1 GA (2026.0.0).</li>
<li><a
href="https://github.com/spring-projects/spring-data-elasticsearch/commit/473caa8214b9879c6a28c3f2ca4b29757b2f61cf"><code>473caa8</code></a>
Missing parts of update to Elasticseach 9.4.2</li>
<li><a
href="https://github.com/spring-projects/spring-data-elasticsearch/commit/33faaa8689b57437ba36e17dc3f6a9edb16985d1"><code>33faaa8</code></a>
Upgrade to Maven Wrapper 3.9.16.</li>
<li><a
href="https://github.com/spring-projects/spring-data-elasticsearch/commit/189611af7f0212c6e9ee1500427d5660cf789b95"><code>189611a</code></a>
Upgrade to Elasticsearch REST Client 9.4.2.</li>
<li><a
href="https://github.com/spring-projects/spring-data-elasticsearch/commit/db2f779ff3df1c4978d7ffdb50bf8ef45da519a1"><code>db2f779</code></a>
Refine GitHub Actions workflows.</li>
<li><a
href="https://github.com/spring-projects/spring-data-elasticsearch/commit/6654eaa38fd06fd2ec24a714612ef442c5c8ad9b"><code>6654eaa</code></a>
Upgrade Elasticsearch client to 9.4.1.</li>
<li><a
href="https://github.com/spring-projects/spring-data-elasticsearch/commit/ebdc57e4b260b01ba0dcda470e7e398a8424813c"><code>ebdc57e</code></a>
Update documentation.</li>
<li><a
href="https://github.com/spring-projects/spring-data-elasticsearch/commit/4cbfef39c69e5f0c215d49e0d75fb9251cfe5ce6"><code>4cbfef3</code></a>
Upgrade to Elasticsearch 9.4.0.</li>
<li><a
href="https://github.com/spring-projects/spring-data-elasticsearch/commit/8ad2e8e0a0e2abc40c80af32392194e9aa9e889a"><code>8ad2e8e</code></a>
nullability-fixes</li>
<li><a
href="https://github.com/spring-projects/spring-data-elasticsearch/commit/795e1ef60a0b1c53f60bb1549861f20d4c24fa7d"><code>795e1ef</code></a>
Refactor routing and null handling with a new getRouting methods.</li>
<li>Additional commits viewable in <a
href="https://github.com/spring-projects/spring-data-elasticsearch/compare/6.0.5...6.1.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.springframework.data:spring-data-elasticsearch&package-manager=maven&previous-version=6.0.5&new-version=6.1.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>