chore(deps): 依赖项升级[org.springframework:spring-core][6.2.11 => 6.2.12] (#430)
Bumps
[org.springframework:spring-core](https://github.com/spring-projects/spring-framework)
from 6.2.11 to 6.2.12.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/spring-projects/spring-framework/releases">org.springframework:spring-core's
releases</a>.</em></p>
<blockquote>
<h2>v6.2.12</h2>
<h2>:star: New Features</h2>
<ul>
<li>Add &quot;forEachByte&quot; variant to DataBuffer for efficient
traversing <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35623">#35623</a></li>
<li>Nested transaction support via savepoints is broken in HSQLDB
database [followup] <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35618">#35618</a></li>
<li>Improve exception handling in
<code>ConfigurationClassBeanDefinitionReader</code> <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35631">#35631</a></li>
<li>Add MySQL/MariaDB to TableMetaDataProviderFactory for correct
generated-keys support <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35593">#35593</a></li>
<li>Optimize state management in StompSubProtocolHandler <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35591">#35591</a></li>
<li>ServletServerHttpRequest.getRemoteAddress() may perform DNS lookup
<a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35589">#35589</a></li>
<li>Emit log message when multiple primary beans are detected <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35550">#35550</a></li>
<li>Duplicate key error is mapped to
<code>TransientDataAccessException</code> by
<code>SQLStateSQLExceptionTranslator</code> for
<code>BatchUpdateException</code> <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35547">#35547</a></li>
<li>Remove redundant object allocation in cglib proxy method calls <a
href="https://redirect.github.com/spring-projects/spring-framework/pull/35543">#35543</a></li>
<li>Remove deprecation on <code>CandidateComponentsIndex</code> and
<code>CandidateComponentsIndexLoader</code> <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35472">#35472</a></li>
<li>Processing response with no Content-Length header and no body raises
EOFException <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35361">#35361</a></li>
</ul>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>DefaultListableBeanFactory::getBeanNamesForType does not always
return all bean names <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35634">#35634</a></li>
<li>Consider defaultCandidate for scoped proxies <a
href="https://redirect.github.com/spring-projects/spring-framework/pull/35627">#35627</a></li>
<li>Release data buffer in AbstractCharSequenceDecoder even when String
creation fails <a
href="https://redirect.github.com/spring-projects/spring-framework/pull/35625">#35625</a></li>
<li>PathMatchingResourcePatternResolver is not able to resolve file in
SpringBoot Packaged JAR <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35617">#35617</a></li>
<li>Prevent NoClassDefFoundError when Jetty Reactive HttpClient is not
available <a
href="https://redirect.github.com/spring-projects/spring-framework/pull/35608">#35608</a></li>
<li>Performance regression with Property Placeholder Resolution <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35594">#35594</a></li>
<li>Retain order of <code>produces</code> media types in
<code>@ExceptionHandler</code> <a
href="https://redirect.github.com/spring-projects/spring-framework/pull/35587">#35587</a></li>
<li>Nested transaction support via savepoints is broken in HSQLDB
database <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35564">#35564</a></li>
<li>SpEL expression parser uses more CPU after upgrade to 6.2.9 <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35556">#35556</a></li>
<li>Thread race during FactoryBean instantiations starting with 6.2 due
to lenient locks <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35545">#35545</a></li>
<li>Update parsed path handling in UrlHandlerFilter <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35538">#35538</a></li>
<li>ResourceHttpMessageWriter.write has unexpected error handling for
invalid range requests (offset &gt; content length) <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35536">#35536</a></li>
<li><code>AbstractTestNGSpringContextTests</code> is not thread-safe
regarding tracked exceptions <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35528">#35528</a></li>
<li>UrlHandlerFilter breaks RequestDispatcher.forward() on Tomcat <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35509">#35509</a></li>
<li>AbstractMockHttpServletRequestBuilder#buildRequest is not idempotent
<a
href="https://redirect.github.com/spring-projects/spring-framework/pull/35493">#35493</a></li>
<li>Add support for <code>JvmDefault</code> (default in Kotlin 2.2.20+)
<a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35487">#35487</a></li>
<li>InstanceSupplierCodeGenerator fails to detect deprecated type on
package private factory method <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35486">#35486</a></li>
<li>Fix synchronization in ResponseBodyEmitter <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35466">#35466</a></li>
<li>useCaches option in PathMatchingResourcePatternResolver not applied
in special case <a
href="https://redirect.github.com/spring-projects/spring-framework/pull/35465">#35465</a></li>
<li>Deadlock during context initialization due to EntityManager lock <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35398">#35398</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Improve guidance in WebFlux on how to join inbound and outbound
streams in <code>WebSocketHandler</code> <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35572">#35572</a></li>
<li>Fix <code>idref</code> example in reference manual <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35560">#35560</a></li>
<li>Fix URI Patterns docs in WebMVC and WebFlux Request Mapping <a
href="https://redirect.github.com/spring-projects/spring-framework/pull/35551">#35551</a></li>
<li>Allow event listener method declared with multiple event classes to
take a single parameter that is assignable from all of those event
classes <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35506">#35506</a></li>
<li>Improve Task Javadoc about Runnable wrapping <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35394">#35394</a></li>
</ul>
<h2>:hammer: Dependency Upgrades</h2>
<ul>
<li>Upgrade to Micrometer 1.14.12 <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35640">#35640</a></li>
<li>Upgrade to Reactor 2024.0.11 <a
href="https://redirect.github.com/spring-projects/spring-framework/issues/35638">#35638</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/e354390837e62c77a7ac386960df33fb357724b8"><code>e354390</code></a>
Release v6.2.12</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/c53132ecdf8a01ad7a4523501d5dae2288fa8d0f"><code>c53132e</code></a>
Polishing</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/03c3ec15774c4de714129222b9b7732b57d96225"><code>03c3ec1</code></a>
Fall back on remoteHost if remoteAddress is null</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/c88bfc54c9256e3c07511aa303be2b136c03e0e2"><code>c88bfc5</code></a>
Refactor state management in StompSubProtocolHandler</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/a96558c965d1a12bf92a816b83228b3597783cf1"><code>a96558c</code></a>
Revise commit 01acb805018da643a3c4320ff0e032aa998beda8</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/1612b7c5dbe53189ed64274571d7c68b61dc4d98"><code>1612b7c</code></a>
Remove test prefixes</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/01acb805018da643a3c4320ff0e032aa998beda8"><code>01acb80</code></a>
Improve exception handling in
ConfigurationClassBeanDefinitionReader</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/f4438ce9e3c0f3c5c2d89a5c8ebf251849943355"><code>f4438ce</code></a>
Upgrade to Reactor 2024.0.11 and Micrometer 1.14.12</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/5033b9d3c5ab88dc33c0d35b096ccb58a5cc59d1"><code>5033b9d</code></a>
Reset by-type cache for Object after registering a new singleton</li>
<li><a
href="https://github.com/spring-projects/spring-framework/commit/d733023a2978a4725c6686645ad2dc05e640266f"><code>d733023</code></a>
Consistently apply fallback attribute to proxy definition as well</li>
<li>Additional commits viewable in <a
href="https://github.com/spring-projects/spring-framework/compare/v6.2.11...v6.2.12">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.springframework:spring-core&package-manager=maven&previous-version=6.2.11&new-version=6.2.12)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>